### ISSUE TITLE
Display current Spanner's status when execute "kubectl get spannerautoscaler"

### ISSUE THREAD

**Issue by w1mvy** [mercari/spanner-autoscaler#58]
Hello. Thank you for the great tool.

## What you want to add

I want to display Spanner's status (current node/current cpu), when execute `kubectl get spannerautoscaler`

## Why this is needed

Now, `kubectl get spannerautoscaler` displayed only the setting values. (target cpu/min node/max node/etc...)
So, If you want to know Spanner' status , you need to display the GCP console, etc. 

I want to be able to check both configuration and setting values at once, like `kubectl get hpa`.

Since I already have [a diff for this feature](https://github.com/mercari/spanner-autoscaler/compare/master...w1mvy:add-column-about-current-status?expand=1), can I create a PR for it?

```
$ kubectl get spannerautoscaler
NAME                 PROJECT ID   INSTANCE ID     MIN NODES   MAX NODES   CURRENT NODES   MIN PUS   MAX PUS   CURRENT PUS   TARGET CPU   CURRENT CPU   AGE
spanner-autoscaler   my-project   test-instance                           0               100       300       100           30           4             3d20h
```

**Comment by rustycl0ck** [comment]
Thank you for suggesting this. Please feel free to create a PR for this 👍

**Comment by w1mvy** [comment]
Thanks your comment. I created a PR!!

**Comment by tkuchiki** [comment]
Thank you for your contribution!
Released 🎉  https://github.com/mercari/spanner-autoscaler/releases/tag/v0.2.3

**Comment by w1mvy** [comment]
Thanks for your quick review and release 👍
